num1 = int(input("Enter value number 1 : "))
num2 = int(input("Enter value number 2 : "))
num3 = int(input("Enter value number 3 : "))
Minvalue = min(num1,num2,num3)
Maxvalue = max(num1,num2,num3)

print()
print("Your enter number : ",num1,num2,num3)
print("Maximum value : ",Maxvalue)
print("Minimum value : ",Minvalue)
print("Average value : ",round(sum((num1,num2,num3))/3,2) )